version: '3.3'
services:
  air-quality:
    image: hongjs/airquality:latest
    restart: always
    environment:
      PORT: 5001
      TARGET_SITE: 'https://www.iqair.com/thailand'
      WAQI_TOKEN: '507269ce-cb1a-4295-b0dd-ee466a36f390'
      AIR4THAI_SITE: 'http://air4thai.com/forweb/getAQI_JSON.php'
    ports:
      - '8082:5001'
    expose:
      - '8082'